---
- name: balanceador
  hosts: all
  become: true
  tasks:
    - name: Actualizar cache APT
      apt:
        update_cache: yes

    - name: Install HAProxy
      apt:
        name: haproxy
        state: present

    - name: Enable haproxy service
      ansible.builtin.systemd:
        name: haproxy
        enabled: yes
        state: started

    - name: Configure HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify:
        - Restart HAProxy

  handlers:
    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted
